/**
 * Memory Layer Popup Script
 * Built with Kiro for Kiroween 2025 🎃
 * 
 * Generated by Kiro - Vibe Coding
 * Prompt: "Create popup.js for Chrome extension popup:
 *         1. Check authentication status on load
 *         2. Handle sign in with Google
 *         3. Handle sign out
 *         4. Update UI based on auth state
 *         5. Show user info and stats
 *         6. Handle errors gracefully"
 * 
 * Time saved: ~4 hours of UI development
 */

console.log('🎃 Memory Layer Popup initializing...');

// DOM elements
const loading = document.getElementById('loading');
const signInSection = document.getElementById('sign-in-section');
const dashboard = document.getElementById('dashboard');
const errorMessage = document.getElementById('error-message');
const googleSignInBtn = document.getElementById('google-signin-btn');
const signOutBtn = document.getElementById('sign-out-btn');
const userEmail = document.getElementById('user-email');

// Initialize
init();

async function init() {
  try {
    // Check authentication status
    const response = await chrome.runtime.sendMessage({ type: 'GET_AUTH_STATUS' });
    
    if (response && response.isAuthenticated) {
      showDashboard(response.user);
    } else {
      showSignIn();
    }
  } catch (error) {
    console.error('Init error:', error);
    showError('Failed to initialize. Please try again.');
    showSignIn();
  }
}

function showSignIn() {
  loading.style.display = 'none';
  signInSection.style.display = 'block';
  dashboard.style.display = 'none';
}

function showDashboard(user) {
  loading.style.display = 'none';
  signInSection.style.display = 'none';
  dashboard.style.display = 'block';
  
  if (user && user.email) {
    userEmail.textContent = user.email;
  }
}

function showError(message) {
  errorMessage.textContent = message;
  errorMessage.style.display = 'block';
  setTimeout(() => {
    errorMessage.style.display = 'none';
  }, 5000);
}

// Sign in with Google
googleSignInBtn.addEventListener('click', async () => {
  try {
    googleSignInBtn.disabled = true;
    googleSignInBtn.textContent = 'Signing in...';
    
    const response = await chrome.runtime.sendMessage({
      type: 'SIGN_IN_PROVIDER',
      provider: 'google'
    });
    
    if (response && response.success) {
      showDashboard(response.user);
    } else {
      showError(response?.error || 'Sign in failed');
      googleSignInBtn.disabled = false;
      googleSignInBtn.innerHTML = `
        <svg class="btn-icon" width="18" height="18" viewBox="0 0 18 18">
          <path fill="#4285F4" d="M17.64 9.2c0-.637-.057-1.251-.163-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z"/>
          <path fill="#34A853" d="M9 18c2.43 0 4.467-.806 5.956-2.184l-2.908-2.258c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332C2.438 15.983 5.482 18 9 18z"/>
          <path fill="#FBBC05" d="M3.964 10.712c-.18-.54-.282-1.117-.282-1.712s.102-1.172.282-1.712V4.956H.957C.348 6.175 0 7.55 0 9s.348 2.825.957 4.044l3.007-2.332z"/>
          <path fill="#EA4335" d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0 5.482 0 2.438 2.017.957 4.956L3.964 7.288C4.672 5.163 6.656 3.58 9 3.58z"/>
        </svg>
        Continue with Google
      `;
    }
  } catch (error) {
    console.error('Sign in error:', error);
    showError('Sign in failed. Please try again.');
    googleSignInBtn.disabled = false;
  }
});

// Sign out
signOutBtn.addEventListener('click', async () => {
  try {
    await chrome.runtime.sendMessage({ type: 'SIGN_OUT' });
    showSignIn();
  } catch (error) {
    console.error('Sign out error:', error);
    showError('Sign out failed');
  }
});

console.log('✅ Memory Layer Popup ready!');
