/**
 * Memory Layer - ChatGPT Content Script
 * Built with Kiro for Kiroween 2025 🎃
 * 
 * Generated by Kiro - Vibe Coding
 * Prompt: "Create content script for ChatGPT integration:
 *         1. Wait for ChatGPT UI to load
 *         2. Create Memory Layer button next to send button
 *         3. Implement 7-step flow
 *         4. Use MutationObserver to detect response completion
 *         5. Show notifications for user feedback"
 * 
 * 7-Step Flow:
 * 1. User clicks Memory Layer button
 * 2. Save prompt to backend
 * 3. Get relevant context
 * 4. Enhance prompt with context
 * 5. Send to ChatGPT
 * 6. Wait for response
 * 7. Save response to backend
 * 
 * Time saved: ~8 hours of DOM manipulation and flow logic
 */

console.log('[Memory Layer] 🎃 Initializing ChatGPT integration...');

let userId = null;
let isAuthenticated = false;
let memoryButton = null;

// Initialize
init();

async function init() {
  // Check authentication
  try {
    const authResponse = await chrome.runtime.sendMessage({ type: 'GET_AUTH_STATUS' });
    isAuthenticated = authResponse?.isAuthenticated || false;
    
    if (isAuthenticated && authResponse?.user) {
      userId = authResponse.user.id;
      console.log('[Memory Layer] ✅ Authenticated:', userId);
    } else {
      console.warn('[Memory Layer] ⚠️  Not authenticated');
      userId = null;
    }
  } catch (error) {
    console.error('[Memory Layer] ❌ Auth check failed:', error);
    userId = null;
  }
  
  // Wait for ChatGPT UI to load
  waitForChatUI();
}

function waitForChatUI() {
  const checkInterval = setInterval(() => {
    const textarea = document.querySelector('#prompt-textarea') ||
                     document.querySelector('textarea[placeholder*="Message"]');
    
    if (textarea) {
      clearInterval(checkInterval);
      console.log('[Memory Layer] Chat UI detected');
      createMemoryButton();
    }
  }, 1000);
}

/**
 * Create Memory Layer button next to send button
 */
function createMemoryButton() {
  const sendButton = document.querySelector('button[data-testid="send-button"]') ||
                     document.querySelector('button[aria-label*="Send"]');
  
  if (!sendButton) {
    console.log('[Memory Layer] Send button not found, retrying...');
    setTimeout(createMemoryButton, 1000);
    return;
  }
  
  // Create button
  memoryButton = document.createElement('button');
  memoryButton.id = 'memory-layer-btn';
  memoryButton.innerHTML = `
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor">
      <circle cx="12" cy="12" r="10" stroke-width="2"/>
      <path d="M12 8v8M8 12h8" stroke-width="2"/>
    </svg>
  `;
  memoryButton.title = 'Memory Layer - Save & Enhance';
  memoryButton.className = 'memory-layer-button';
  
  // Add click handler
  memoryButton.addEventListener('click', handleMemoryClick);
  
  // Insert next to send button
  sendButton.parentElement.insertBefore(memoryButton, sendButton);
  
  console.log('[Memory Layer] ✅ Button created!');
}

/**
 * STEP 1: Handle Memory Layer button click
 */
async function handleMemoryClick(event) {
  event.preventDefault();
  event.stopPropagation();
  
  console.log('[Memory Layer] ==========================================');
  console.log('[Memory Layer] STEP 1: Button clicked!');
  
  // Check authentication
  if (!isAuthenticated || !userId) {
    showNotification('❌ Please sign in first');
    return;
  }
  
  // Get user's prompt
  const textarea = document.querySelector('#prompt-textarea') ||
                   document.querySelector('textarea[placeholder*="Message"]');
  
  if (!textarea) {
    showNotification('❌ Could not find text input');
    return;
  }
  
  const promptText = textarea.value || textarea.textContent || textarea.innerText;
  
  if (!promptText || promptText.trim().length === 0) {
    showNotification('❌ Please type a message first');
    return;
  }
  
  const originalPrompt = promptText.trim();
  console.log('[Memory Layer] Original prompt:', originalPrompt.substring(0, 100));
  
  // Disable button during processing
  memoryButton.disabled = true;
  memoryButton.style.opacity = '0.5';
  showNotification('⏳ Processing...');
  
  try {
    await executeFlow(originalPrompt, textarea);
  } catch (error) {
    console.error('[Memory Layer] Error:', error);
    showNotification('❌ Error: ' + error.message);
  } finally {
    memoryButton.disabled = false;
    memoryButton.style.opacity = '1';
  }
}

/**
 * Execute 7-step flow
 */
async function executeFlow(originalPrompt, textarea) {
  // STEP 2 & 3: Save prompt and get context in parallel
  console.log('[Memory Layer] STEP 2 & 3: Saving prompt & getting context...');
  
  const [saveResult, contextResult] = await Promise.all([
    savePrompt(originalPrompt),
    getContext(originalPrompt)
  ]);
  
  console.log('[Memory Layer] ✅ STEP 2: Prompt saved');
  console.log('[Memory Layer] ✅ STEP 3: Context retrieved -', contextResult.length, 'items');
  
  // STEP 4: Enhance prompt with context
  let enhancedPrompt = originalPrompt;
  
  if (contextResult.length > 0) {
    const contextStr = contextResult.join('\n- ');
    enhancedPrompt = `Based on what you know about me from our previous conversations:
- ${contextStr}

Answer this question: ${originalPrompt}`;
    console.log('[Memory Layer] ✅ STEP 4: Prompt enhanced with context');
  } else {
    console.log('[Memory Layer] ⏭️  STEP 4: No context found');
  }
  
  // Update textarea
  if (textarea.value !== undefined) {
    textarea.value = enhancedPrompt;
  } else {
    textarea.textContent = enhancedPrompt;
  }
  textarea.dispatchEvent(new Event('input', { bubbles: true }));
  
  // STEP 5: Click send button
  console.log('[Memory Layer] STEP 5: Sending to ChatGPT...');
  
  const sendButton = document.querySelector('button[data-testid="send-button"]') ||
                     document.querySelector('button[aria-label*="Send"]');
  
  if (!sendButton) {
    throw new Error('Send button not found');
  }
  
  // Store original prompt for Step 7
  window.memoryLayerOriginalPrompt = originalPrompt;
  window.memoryLayerWaitingForResponse = true;
  
  // Click send
  setTimeout(() => {
    sendButton.click();
    console.log('[Memory Layer] ✅ STEP 5: Sent to ChatGPT');
    showNotification('🚀 Sent with memory!');
    
    // Start observing for response
    observeForResponse();
  }, 200);
}

/**
 * API: Save prompt
 */
async function savePrompt(prompt) {
  const response = await chrome.runtime.sendMessage({
    type: 'SAVE_PROMPT',
    data: {
      prompt: prompt,
      provider: 'chatgpt'
    }
  });
  
  if (!response || !response.success) {
    throw new Error(response?.error || 'Save prompt failed');
  }
  return response.data;
}

/**
 * API: Get context
 */
async function getContext(query) {
  try {
    const response = await chrome.runtime.sendMessage({
      type: 'GET_CONTEXT',
      query: query
    });
    
    if (!response || !response.success) {
      console.error('[Memory Layer] Context retrieval failed:', response?.error);
      return [];
    }
    
    return response.contexts || [];
  } catch (error) {
    console.error('[Memory Layer] Context retrieval failed:', error);
    return [];
  }
}

/**
 * API: Save response
 */
async function saveResponse(prompt, responseText) {
  const result = await chrome.runtime.sendMessage({
    type: 'SAVE_RESPONSE',
    data: {
      prompt: prompt,
      response: responseText,
      provider: 'chatgpt'
    }
  });
  
  if (!result || !result.success) {
    throw new Error(result?.error || 'Save response failed');
  }
  return result.data;
}

/**
 * STEP 6: Observe for ChatGPT response
 */
function observeForResponse() {
  console.log('[Memory Layer] STEP 6: Waiting for response...');
  
  const observer = new MutationObserver(() => {
    if (!window.memoryLayerWaitingForResponse) return;
    
    // Find latest assistant message
    const messages = document.querySelectorAll('[data-message-author-role="assistant"]');
    if (messages.length === 0) return;
    
    const lastMessage = messages[messages.length - 1];
    
    // Check if still streaming
    const isStreaming = lastMessage.querySelector('[data-testid="streaming-indicator"]');
    if (isStreaming) return;
    
    // Response is complete
    const responseText = lastMessage.querySelector('.markdown')?.textContent ||
                         lastMessage.textContent;
    
    if (!responseText || !responseText.trim()) return;
    
    // Stop observing
    window.memoryLayerWaitingForResponse = false;
    observer.disconnect();
    
    console.log('[Memory Layer] ✅ STEP 6: Response received');
    
    // STEP 7: Save response
    saveTheResponse(responseText);
  });
  
  observer.observe(document.body, {
    childList: true,
    subtree: true
  });
}

/**
 * STEP 7: Save response
 */
async function saveTheResponse(responseText) {
  console.log('[Memory Layer] STEP 7: Saving response...');
  
  try {
    await saveResponse(window.memoryLayerOriginalPrompt, responseText);
    
    console.log('[Memory Layer] ✅ STEP 7: Response saved!');
    console.log('[Memory Layer] ==========================================');
    
    showNotification('💾 Memory saved!');
    
    delete window.memoryLayerOriginalPrompt;
  } catch (error) {
    console.error('[Memory Layer] Save response failed:', error);
    showNotification('❌ Save failed');
  }
}

/**
 * Show notification
 */
function showNotification(message) {
  const notif = document.createElement('div');
  notif.className = 'memory-layer-notification';
  notif.textContent = message;
  document.body.appendChild(notif);
  
  setTimeout(() => notif.classList.add('show'), 10);
  setTimeout(() => {
    notif.classList.remove('show');
    setTimeout(() => notif.remove(), 300);
  }, 2500);
}

console.log('[Memory Layer] Ready! 🎃');
